=== hmrc/individuals-charges-api/resources/public/api/conf/1.0/schemas/retrievePensionCharges/retrieve_pension_charges_response.json
{
  "$schema":"http://json-schema.org/draft-04/schema#",
  "title":"Retrieve Pension Charges",
  "description":"Retrieve Pension Charges",
  "properties":{
    "pensionSavingsTaxCharges":{
      "type":"object",
      "description":"Object holding the booleans for annual allowance.",
      "properties":{
        "isAnnualAllowanceReduced":{
          "description":"A boolean indicating whether annual allowance has been reduced. The value must be true or false.",
          "type":"boolean",
          "example":"false"
        },
        "taperedAnnualAllowance":{
          "description":"A boolean indicating whether tapered annual allowance is lower than the standard annual allowance. The value must be true or false.",
          "type":"boolean",
          "example":"true"
        },
        "moneyPurchasedAllowance":{
          "description":"A boolean indicating whether money purchased allowance has been paid. The value must be true or false.",
          "type":"boolean",
          "example":"false"
        },
        "pensionSchemeTaxReference":{
          "description":"The unique reference provided by HM Revenue and Customs (HMRC) when the scheme has been registered for tax relief and exemptions. It is 10 characters made up of 8 numbers followed by 2 letters.",
          "type":"array",
          "example":"00123456RA"
        },
        "lumpSumBenefitTakenInExcessOfLifetimeAllowance":{
          "type":"object",
          "description":"The amount and tax paid on lump sum benefit in excess of the lifetime allowance.",
          "properties":{
            "amount":{
              "description":"The amount of the lump sum benefit taken in excess of the lifetime allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type":"number",
              "example":"1999.99"
            },
            "taxPaid":{
              "description":"The amount of tax to be paid on the lump sum benefit taken in excess of the lifetime allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type":"number",
              "example":"1999.99"
            }
          }
        },
        "benefitInExcessOfLifetimeAllowance":{
          "type":"object",
          "description":"The amount and tax paid on benefit in excess of the lifetime allowance.",
          "properties":{
            "amount":{
              "description":"The amount of the benefit taken in excess of the lifetime allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type":"number",
              "example":"1999.99"
            },
            "taxPaid":{
              "description":"The tax to be paid on the benefit taken in excess of the lifetime allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type":"number",
              "example":"1999.99"
            }
          }
        }
      },
      "required":[
        "pensionSchemeTaxReference"
      ]
    },
    "pensionSchemeOverseasTransfers":{
      "type":"object",
      "description":"Transfer of overseas pension to another pension scheme.",
      "properties":{
        "overseasSchemeProvider":{
          "description":"Details of the overseas pension provider.",
          "type":"array",
          "items":{
            "providerName":{
              "description":"The name of the pension provider.",
              "type":"string",
              "example":"Overseas Pensions Plc"
            },
            "providerAddress":{
              "description":"The address of the pension provider.",
              "type":"string",
              "example":"111 Main Street, Any Town, Any City"
            },
            "providerCountryCode":{
              "description":"A three-letter code that represents a country name. The value must be a ISO 3166-1 alpha-3 code.",
              "type":"string",
              "example":"CYM"
            },
            "qualifyingRecognisedOverseasPensionScheme":{
              "description":"Array of qualifying recognised Overseas Pension Scheme reference number.",
              "type":"array",
              "example":"Q123456"
            }
          }
        },
        "transferCharge":{
          "description":"The amount the pension provider charges to transfer the pension. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type":"number",
          "example":"1999.99"
        },
        "transferChargeTaxPaid":{
          "description":"The amount of tax paid on the transfer charge. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type":"number",
          "example":"1999.99"
        }
      }
    },
    "pensionSchemeUnauthorisedPayments":{
      "type":"object",
      "description":"Tax on unauthorised payment.",
      "properties":{
        "pensionSchemeTaxReference":{
          "description":"The unique reference provided by HM Revenue and Customs (HMRC) when the scheme has been registered for tax relief and exemptions. It is 10 characters made up of 8 numbers followed by 2 letters.",
          "type":"array",
          "example":"00123456RA"
        },
        "surcharge":{
          "type":"object",
          "description":"The unauthorised payments surcharge.",
          "properties":{
            "amount":{
              "description":"The amount of the unauthorised payment. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type":"number",
              "example":"1999.99"
            },
            "foreignTaxPaid":{
              "description":"The amount of foreign tax paid in pounds sterling. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type":"number",
              "example":"1999.99"
            }
          }
        },
        "noSurcharge":{
          "type":"object",
          "description":"The unauthorised payments no surcharge.",
          "properties":{
            "amount":{
              "description":"The amount of the unauthorised payment. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type":"number",
              "example":"1999.99"
            },
            "foreignTaxPaid":{
              "description":"The amount of foreign tax paid in pounds sterling. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
              "type":"number",
              "example":"1999.99"
            }
          }
        }
      }
    },
    "pensionContributions":{
      "type":"object",
      "description":"Payments paid into a pension",
      "properties":{
        "pensionSchemeTaxReference":{
          "description":"The unique reference provided by HM Revenue and Customs (HMRC) when the scheme has been registered for tax relief and exemptions. It is 10 characters made up of 8 numbers followed by 2 letters.",
          "type":"array",
          "example":"00123456RA"
        },
        "inExcessOfTheAnnualAllowance":{
          "description":"The amount of the in excess of the annual allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type":"number",
          "example":"1999.99"
        },
        "annualAllowanceTaxPaid":{
          "description":"The amount of tax paid on annual allowance. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type":"number",
          "example":"1999.99"
        }
      }
    },
    "overseasPensionContributions":{
      "type":"object",
      "description":"Contributions paid into overseas pension.",
      "properties":{
        "overseasSchemeProvider":{
          "description":"Details of the overseas pension provider.",
          "type":"array",
          "items":{
            "providerName":{
              "description":"The name of the pension provider.",
              "type":"string",
              "example":"Overseas Pensions Plc"
            },
            "providerAddress":{
              "description":"The address of the pension provider.",
              "type":"string",
              "example":"111 Main Street, Any Town, Any City"
            },
            "providerCountryCode":{
              "description":"A three-letter code that represents a country name. The value must be a ISO 3166-1 alpha-3 code.",
              "type":"string",
              "example":"CYM"
            },
            "qualifyingRecognisedOverseasPensionScheme":{
              "description":"Array of qualifying recognised Overseas Pension Scheme reference number.",
              "type":"array",
              "example":"Q123456"
            }
          }
        },
        "shortServiceRefund":{
          "description":"The amount of short service refund for overseas pension contributions. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type":"number",
          "example":"1999.99"
        },
        "shortServiceRefundTaxPaid":{
          "description":"The amount of tax paid on short service refund. The value must be between 0 and 99999999999.99 up to 2 decimal places.",
          "type":"number",
          "example":"1999.99"
        }
      }
    }
  }
}

=== hmrc/individuals-charges-api/resources/public/api/conf/3.0/examples/pensionCharges/createAmend/def1/create_amend_request.json
{
  "pensionSavingsTaxCharges": {
    "pensionSchemeTaxReference": [
      "00123456RA",
      "00123456RA"
    ],
    "lumpSumBenefitTakenInExcessOfLifetimeAllowance": {
      "amount": 100,
      "taxPaid": 100
    },
    "benefitInExcessOfLifetimeAllowance": {
      "amount": 100,
      "taxPaid": 100
    }
  },
  "pensionSchemeOverseasTransfers": {
    "overseasSchemeProvider": [
      {
        "providerName": "Overseas Pensions Plc",
        "providerAddress": "111 Main Street, George Town, Grand Cayman",
        "providerCountryCode": "CYM",
        "qualifyingRecognisedOverseasPensionScheme": [
          "Q123456"
        ]
      }
    ],
    "transferCharge": 100,
    "transferChargeTaxPaid": 100
  },
  "pensionSchemeUnauthorisedPayments": {
    "pensionSchemeTaxReference": [
      "00123456RA",
      "00123456RA"
    ],
    "surcharge": {
      "amount": 100,
      "foreignTaxPaid": 100
    },
    "noSurcharge": {
      "amount": 100,
      "foreignTaxPaid": 100
    }
  },
  "pensionContributions": {
    "pensionSchemeTaxReference": [
      "00123456RA",
      "00123456RA"
    ],
    "inExcessOfTheAnnualAllowance": 100,
    "annualAllowanceTaxPaid": 100,
    "isAnnualAllowanceReduced": true,
    "taperedAnnualAllowance": true,
    "moneyPurchasedAllowance": false
  },
  "overseasPensionContributions": {
    "overseasSchemeProvider": [
      {
        "providerName": "Overseas Pensions Plc",
        "providerAddress": "111 Main Street, George Town, Grand Cayman",
        "providerCountryCode": "CYM",
        "qualifyingRecognisedOverseasPensionScheme": [
          "Q123456"
        ]
      }
    ],
    "shortServiceRefund": 123.0,
    "shortServiceRefundTaxPaid": 123.0
  }
}
